# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cedf8f2624395133a32fabef73bac6e5324a2fd6f4332bbaf52ec699ae4113115f4c068fa662486fa0932d6a10c12996b9354be60d346f5a55040ef50b55cbb

test:
  secret_key_base: 9d4d4d1a4611b56b769d1f44418c1f36ac5a13bb5a3402f837d9667a607e984d2ce617d048533e67d9fc190cecba7eb5042a78d801e559145517072a513cbe62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
